### ISSUE TITLE
Remove the workaround for gcc.99578?

### ISSUE THREAD

**Issue by Chandlerooo** [xcd0/qmk_firmware#1]
I notice a workaround for gcc.99578 in tmk_core/common/chibios/bootloader.c introduced by commit https://github.com/xcd0/qmk_firmware/commit/a535d24ecfd465124cdb255e53b5cc301cbda6d9
https://github.com/xcd0/qmk_firmware/blob/014aa0661e2d9cf5b67334f82869d4a841cc703f/tmk_core/common/chibios/bootloader.c#L106-L107
This bug has been marked as fixed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578. Shall it be removed?

**Comment by xcd0** [comment]
I apologize for the delayed response.
This repository is almost unmaintained, so I am considering archiving it.
Thank you for raising the issue.
